package snapshot

import (
	"context"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
)

// DefaultBtrbkConfPath is where `apply` writes the rendered btrbk.conf and where
// the engine points btrbk via `-c`.
const DefaultBtrbkConfPath = "/etc/bentoo/btrbk.conf"

// btrbkEngine drives btrbk. Snapshot creation/pruning/listing shell out via the
// Runner seam; the destructive work stays inside btrbk (AD1). The engine does not
// write the conf itself — that is done at `apply`/`run` time (writeBtrbkConf) so
// Create/Prune/List remain pure subprocess calls and fully mockable.
type btrbkEngine struct {
	cfg      EngineConfig
	targets  []string // ssh remote targets contributed by shippers (AD5)
	run      Runner
	confPath string
}

// newBtrbkEngine builds the btrbk engine. A nil Runner falls back to the
// production execRunner.
func newBtrbkEngine(cfg EngineConfig, targets []string, run Runner) *btrbkEngine {
	if run == nil {
		run = defaultRunner()
	}
	return &btrbkEngine{cfg: cfg, targets: targets, run: run, confPath: DefaultBtrbkConfPath}
}

func (e *btrbkEngine) Name() string { return "btrbk" }

// Create runs `btrbk run <subvolume>` against the rendered conf (R2.2). The
// snapshot (and any configured send) is performed by btrbk; a non-zero exit is
// wrapped with ErrEngineFailed so the Manager can record a failed stage (§6).
func (e *btrbkEngine) Create(ctx context.Context, subvolume string) (Snapshot, error) {
	args := []string{"-c", e.confPath, "run", subvolume}
	if _, err := e.run.Run(ctx, "btrbk", args, nil); err != nil {
		return Snapshot{}, errors.Join(ErrEngineFailed, fmt.Errorf("btrbk run %s: %w", subvolume, err))
	}
	return Snapshot{Subvolume: subvolume}, nil
}

// Prune runs `btrbk clean <subvolume>` (R2.3). Retention is delegated to btrbk via
// the conf's snapshot_preserve/target_preserve directives (AD6), so the policy
// argument is accepted but not re-applied here.
func (e *btrbkEngine) Prune(ctx context.Context, subvolume string, _ Retention) ([]Snapshot, error) {
	args := []string{"-c", e.confPath, "clean", subvolume}
	if _, err := e.run.Run(ctx, "btrbk", args, nil); err != nil {
		return nil, errors.Join(ErrEngineFailed, fmt.Errorf("btrbk clean %s: %w", subvolume, err))
	}
	return nil, nil
}

// List runs `btrbk list <subvolume>` and parses the output into snapshots (R5.4).
func (e *btrbkEngine) List(ctx context.Context, subvolume string) ([]Snapshot, error) {
	out, err := e.run.Run(ctx, "btrbk", []string{"-c", e.confPath, "list", subvolume}, nil)
	if err != nil {
		return nil, errors.Join(ErrEngineFailed, fmt.Errorf("btrbk list %s: %w", subvolume, err))
	}
	return parseBtrbkList(out, subvolume), nil
}

// ListRemote lists the backups present on the btrbk targets via
// `btrbk -c <conf> list backups` (008 R5.2). Targets are the ssh ship entries
// folded into btrbk.conf (AD5), so target-side enumeration belongs to this
// engine; with no targets configured there is no remote and no subprocess runs.
// Rows are parsed with the same first-field-absolute-path logic as List. The
// Subvolume attribution is left empty: a target holds backups of every
// subvolume and btrbk's first column is the backup path, not the source.
func (e *btrbkEngine) ListRemote(ctx context.Context) ([]Snapshot, error) {
	if len(e.targets) == 0 {
		return nil, nil
	}
	out, err := e.run.Run(ctx, "btrbk", []string{"-c", e.confPath, "list", "backups"}, nil)
	if err != nil {
		return nil, errors.Join(ErrEngineFailed, fmt.Errorf("btrbk list backups: %w", err))
	}
	return parseBtrbkList(out, ""), nil
}

// Compile-time assertion: the btrbk engine contributes to `list --remote`.
var _ remoteLister = (*btrbkEngine)(nil)

// parseBtrbkList extracts snapshots from `btrbk list` output. Each data line's
// first whitespace field is the snapshot path; header/blank lines and any field
// that is not an absolute path are skipped. The snapshot ID is the path's base
// name. (Real-world btrbk output formats are exercised by the gated live test.)
func parseBtrbkList(out []byte, subvolume string) []Snapshot {
	var snaps []Snapshot
	for _, line := range strings.Split(string(out), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		path := fields[0]
		if !strings.HasPrefix(path, "/") {
			continue
		}
		snaps = append(snaps, Snapshot{
			ID:        filepath.Base(path),
			Subvolume: subvolume,
			Path:      path,
		})
	}
	return snaps
}

// renderBtrbkConf renders a btrbk.conf from the engine config, retention policy,
// and any ssh targets (R2, R2.2, R2.3, AD5, AD6). Retention counts map to btrbk's
// snapshot_preserve/target_preserve grammar; zero counts are omitted.
func renderBtrbkConf(cfg EngineConfig, targets []string) string {
	var b strings.Builder
	b.WriteString("# Generated by bentoo snapshot — do not edit by hand.\n")

	if cfg.SnapshotDir != "" {
		fmt.Fprintf(&b, "snapshot_dir            %s\n", cfg.SnapshotDir)
	}

	preserveMin := cfg.Retention.PreserveMin
	if preserveMin == "" {
		preserveMin = "latest"
	}
	fmt.Fprintf(&b, "snapshot_preserve_min   %s\n", preserveMin)
	if line := retentionLine(cfg.Retention); line != "" {
		fmt.Fprintf(&b, "snapshot_preserve       %s\n", line)
	}

	if len(targets) > 0 {
		fmt.Fprintf(&b, "target_preserve_min     %s\n", preserveMin)
		if line := retentionLine(cfg.Retention); line != "" {
			fmt.Fprintf(&b, "target_preserve         %s\n", line)
		}
	}

	b.WriteString("\n")
	for _, sv := range cfg.Subvolumes {
		fmt.Fprintf(&b, "subvolume %s\n", sv)
	}

	if len(targets) > 0 {
		b.WriteString("\n")
		for _, t := range targets {
			fmt.Fprintf(&b, "target ssh://%s\n", t)
		}
	}

	return b.String()
}

// retentionLine renders the nonzero retention counts as a btrbk preserve line
// (e.g. "24h 7d 4w 6m"). Empty when no counts are set.
func retentionLine(r Retention) string {
	var parts []string
	if r.Hourly > 0 {
		parts = append(parts, fmt.Sprintf("%dh", r.Hourly))
	}
	if r.Daily > 0 {
		parts = append(parts, fmt.Sprintf("%dd", r.Daily))
	}
	if r.Weekly > 0 {
		parts = append(parts, fmt.Sprintf("%dw", r.Weekly))
	}
	if r.Monthly > 0 {
		parts = append(parts, fmt.Sprintf("%dm", r.Monthly))
	}
	return strings.Join(parts, " ")
}

// writeBtrbkConf renders and atomically writes the btrbk.conf to path (0644).
// Used by the `apply` and `run` verbs to materialize the native config.
func writeBtrbkConf(path string, cfg EngineConfig, targets []string) error {
	return atomicWrite(path, []byte(renderBtrbkConf(cfg, targets)), 0o644)
}
